server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartjobsdb
    username: your_db_user
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin123
